const emailData = [
    {
        "mid": "209834578",
        "year": "2013",
        "month": "3",
        "day": "12",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "235",
        "sender": "Lexie",
        "rcpt": "Lucie",
        "rcpt_count": "1",
        "size": "9087",
        "files": "sunlife internal",
        "files_sensitive_count": "1",
        "subject": "urgent",
        "lev_mail": "1",
        "file count": "2",
        "division": "sunlife",
        "employee_status ": "active"
    },
    {
        "mid": "209834579",
        "year": "2014",
        "month": "4",
        "day": "13",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "345",
        "sender": "Louis",
        "rcpt": "Ellie",
        "rcpt_count": "1",
        "size": "9087",
        "files": "business schedule",
        "files_sensitive_count": "1",
        "subject": "urgent",
        "lev_mail": "1",
        "file count": "2",
        "division": "sunlife",
        "employee_status ": "active"
    },
    {
        "mid": "209834580",
        "year": "2015",
        "month": "5",
        "day": "14",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "2745",
        "sender": "Haley",
        "rcpt": "Oscar",
        "rcpt_count": "1",
        "size": "9087",
        "files": "random picture",
        "files_sensitive_count": "1",
        "subject": "urgent",
        "lev_mail": "1",
        "file count": "2",
        "division": "sunlife",
        "employee_status ": "active"
    },
    {
        "mid": "209834581",
        "year": "2016",
        "month": "5",
        "day": "15",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "234",
        "sender": "Larry",
        "rcpt": "Shirley",
        "rcpt_count": "1",
        "size": "9087",
        "files": "important notice",
        "files_sensitive_count": "1",
        "subject": "urgent",
        "lev_mail": "1",
        "file count": "2",
        "division": "sunlife",
        "employee_status ": "active"
    },
    {
        "mid": "209834582",
        "year": "2017",
        "month": "5",
        "day": "16",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "1234",
        "sender": "Sharon",
        "rcpt": "Jackson",
        "rcpt_count": "1",
        "size": "9087",
        "files": "important notice",
        "files_sensitive_count": "1",
        "subject": "urgent",
        "lev_mail": "1",
        "file count": "2",
        "division": "sunlife",
        "employee_status ": "active"
    },
    {
        "mid": "209834583",
        "year": "2018",
        "month": "5",
        "day": "17",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "2345",
        "sender": "Stacy",
        "rcpt": "Tony",
        "rcpt_count": "1",
        "size": "9087",
        "files": "business document",
        "files_sensitive_count": "1",
        "subject": "urgent",
        "lev_mail": "1",
        "file count": "2",
        "division": "sunlife",
        "employee_status ": "active"
    },
    {
        "mid": "209834584",
        "year": "2019",
        "month": "5",
        "day": "18",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "747",
        "sender": "Tuntun",
        "rcpt": "Blanc",
        "rcpt_count": "1",
        "size": "9087",
        "files": "important notice",
        "files_sensitive_count": "1",
        "subject": "urgent",
        "lev_mail": "1",
        "file count": "2",
        "division": "sunlife",
        "employee_status ": "active"
    },
    {
        "mid": "209834585",
        "year": "2020",
        "month": "5",
        "day": "19",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "76",
        "sender": "Keivan",
        "rcpt": "Reem",
        "rcpt_count": "1",
        "size": "9087",
        "files": "quick notice",
        "files_sensitive_count": "1",
        "subject": "urgent",
        "lev_mail": "1",
        "file count": "2",
        "division": "sunlife",
        "employee_status ": "active"
    },
    {
        "mid": "209834586",
        "year": "2021",
        "month": "5",
        "day": "20",
        "hour": "3",
        "minute": "3",
        "day_since_hire": "247",
        "sender": "Kylie",
        "rcpt": "Elvis",
        "rcpt_count": "1",
        "size": "9087",
        "files": "random files",
        "files_sensitive_count": "1",
        "subject": "urgent",
        "lev_mail": "1",
        "file count": "2",
        "division": "sunlife",
        "employee_status ": "active"
    }
]

export default emailData